//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOO_Obuv.AppConnectData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Id_Tovar { get; set; }
        public string Articul { get; set; }
        public string Name_Tovar { get; set; }
        public string Ed_Izmeren { get; set; }
        public Nullable<short> Stoimost { get; set; }
        public string Postavshik { get; set; }
        public string Proizvoditel { get; set; }
        public string Kategoria_Tovara { get; set; }
        public Nullable<byte> Discount { get; set; }
        public Nullable<byte> Kol_vo_na_sclade { get; set; }
        public string Opisanie_Tovara { get; set; }
        public string Image { get; set; }
    }
}
